## Exercise 1 - Create a new 3x3 matrix. Extract 2 values via indexing.

    [[1402,191],
     [1371,821],
     [949,1437]]
     

In [4]:
import numpy as np

1437

In [6]:
ex1 = np.array([
    [1402,191],
    [1371,821],
    [949,1437]])
print (ex1[2][1])
print (ex1[0][1])

1437
191


## Exercise 2 - Add, Subtract, Multiply and Divide 2 Matrices

    [[0, 4],
     [2, 0]]

    [[-1, 2],
     [1, -2]]

In [67]:
ex21 = np.array([
    [0, 4],
    [2, 0]])
ex22 = np.array([
    [-1, 2],
    [1, -2]])

#     [ 0, 4] [-1, 2]
#     [ 2, 0] [ 1,-2]

ans1 = np.array([[-1,6], [3,-2]])
ans2 = np.array([[1,2], [1,2]])
ans3_proper = np.array([
    [0*(-1) + 4*1, 0*2 + 4*(-2)], 
    [2*(-1) + 0*1, 2*2 + 0*(-2)]
    ])

ans3 = np.array([[0,8], [2,0]])
ans4 = np.array([[0,2], [2,0]])

print (ex2_1 + ex2_2 == ans1)
print (ex2_1 - ex2_2 == ans2)
print (ex2_1 * ex2_2 == ans31)
print (ex2_1 / ex2_2 == ans41)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


## Exercise 3 - Create a 3x3 Identity Matrix. Show that for any matrix A, AI=IA=A.

    [[4,2,1],
     [4,8,3],
     [1,1,0]]

In [74]:
ex3 = np.array([
    [4,2,1],
    [4,8,3],
    [1,1,0]])

id3 = np.identity(3, dtype=int)
ai = np.dot(id3, ex3)
ia = np.dot(id3, ai)

print (ex3 == ia)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Exercise 4 - Transpose a Matrix. What do we need to pivot a matrix?

    [[0 1]
     [2 3]
     [4 5]]

In [78]:
ex4 = np.array([
    [0, 1],
    [2, 3],
    [4, 5]])
ex4_t = ex4.T
print (ex4_t)

[[0 2 4]
 [1 3 5]]


## Exercise 5 - Invert a Matrix. What happens when a matrix is not invertible?

    [[1, 4],
     [2, 0]]

In [106]:
ex5 = np.array([
    [1, 4],
    [2, 0]])
ex5_i = np.linalg.inv(ex5)
print (ex5_i)

try:
    ex21_i = np.linalg.inv(ex22)
    print (ex21_i)
except Exception as e:
    print ('"%s" exception is thrown'%  e)
    

[[ 0.     0.5  ]
 [ 0.25  -0.125]]
"Singular matrix" exception is thrown


## Exercise 6 - Find the determinant for the following 3 matrices.

        [[1, 2], 
         [3, 4]], 
        
        [[1, 2], 
         [2, 1]],
        
        [[1, 3],
         [3, 1]]

In [136]:
ex61 = np.array([
    [1, 2], 
    [3, 4]])
ex62 = np.array([
    [1, 2],
    [2, 1]])
ex63 = np.array([
    [1, 3],
    [3, 1]])

d61 = 1*4 - 2*3
d62 = 1*1 - 2*2
d63 = 1*1 - 3*3

print (int(np.linalg.det(ex61)) == d61, d61)
print (int(np.linalg.det(ex62)) == d62, d62, np.linalg.det(ex62))
print (int(np.linalg.det(ex63)) == d63, d63)

True -2
False -3 -3.0
True -8


## Exercise 6 - Solve the following linear system.

- 3x + y = 9
- x + 2y = 8

In [144]:
ex6_sys = np.array([
    [3, 1],
    [1, 2]
    ])
ex6_ans = np.array([9,8])
ex6_sys_i = np.linalg.inv(ex6_sys)
ex6_key = np.dot(ex6_ans, ex6_sys_i)
print (ex6_key)

[ 2.  3.]


## Exercise 7 - Compute the eigenvalues and eigenvectors for the following matrix. What do these represent?

    [[1, 2, 1],
     [6, -1, 0],
     [-1, -2, -1]]

In [148]:
ex7 = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, -2, -1]
    ])
print(np.linalg.eig(ex7)[0])
print(np.linalg.eig(ex7)[1])

[ -4.00000000e+00   3.00000000e+00   1.71642331e-16]
[[ 0.40824829 -0.48507125 -0.0696733 ]
 [-0.81649658 -0.72760688 -0.41803981]
 [-0.40824829  0.48507125  0.90575292]]
